'use strict';

/**
 * Minified AudioWorklet processor source, embedded as a string for Blob URL loading.
 *
 * THIS IS THE CODE THAT ACTUALLY RUNS IN THE BROWSER.
 * The readable version is in worklet-processor.js (documentation/reference only).
 * If worklet-processor.js logic changes, this string MUST be regenerated.
 *
 * Logic identical to worklet-processor.js.
 */
const WORKLET_SOURCE = "var e=class extends AudioWorkletProcessor{constructor(e){super();let t=e.processorOptions;this.framesPerBuffer=t.framesPerBuffer,this.format=t.format,this.native=t.nativeSampleRate,this.target=t.targetSampleRate,this.needsResample=t.nativeSampleRate!==t.targetSampleRate,this.channelMap=t.channelMap??null,this.channels=this.channelMap?this.channelMap.length:t.channels??1,this.channelError=!1,this.phase=0,this.last=new Float32Array(this.channels),this.planar=Array(this.channels),this.mono=null,this.samplesPerChunk=this.framesPerBuffer*this.channels,this.buffer=new Float32Array(this.samplesPerChunk),this.bufferIndex=0}process(e,t,n){let r=e[0];if(!r||r.length===0||!r[0]||r[0].length===0)return!0;if(this.channelError)return!1;let i=r.length,a=this.planar;if(this.channelMap){for(let e=0;e<this.channelMap.length;e++)if(this.channelMap[e]>=i)return this.refuse(`the channel map names device channel `+this.channelMap[e]+`; the device reports `+i+` input channels`);for(let e=0;e<this.channelMap.length;e++)a[e]=r[this.channelMap[e]]}else if(this.channels===1)if(i===1)a[0]=r[0];else{let e=r[0].length;(this.mono===null||this.mono.length!==e)&&(this.mono=new Float32Array(e));let t=this.mono;for(let n=0;n<e;n++){let e=0;for(let t=0;t<i;t++)e=Math.fround(e+r[t][n]);t[n]=e/i}a[0]=t}else if(this.channels===i)for(let e=0;e<i;e++)a[e]=r[e];else if(this.channels>i)return this.refuse(`the input device does not support `+this.channels+` delivered channels; it reports `+i);else return this.refuse(`a channel map is required to deliver `+this.channels+` of the device's `+i+` input channels`);return this.needsResample?this.resample(a):this.accumulate(a),!0}accumulate(e){let t=e[0].length,n=this.channels;for(let r=0;r<t;r++){for(let t=0;t<n;t++)this.buffer[this.bufferIndex++]=e[t][r];this.bufferIndex>=this.samplesPerChunk&&this.flush()}}refuse(e){return this.channelError=!0,this.port.postMessage({type:`error`,message:e}),!1}resample(e){let t=e[0].length,n=this.channels,r=this.native,i=this.target,a=this.last,o=this.phase,s=(t-1)*i;for(;o<s;){let t=Math.floor(o/i),s=(o-t*i)/i;if(t<0)for(let t=0;t<n;t++)this.buffer[this.bufferIndex++]=a[t]*(1-s)+e[t][0]*s;else for(let r=0;r<n;r++)this.buffer[this.bufferIndex++]=e[r][t]*(1-s)+e[r][t+1]*s;this.bufferIndex>=this.samplesPerChunk&&this.flush(),o+=r}this.phase=o-t*i;for(let r=0;r<n;r++)a[r]=e[r][t-1]}flush(){let e;if(this.format===`int16`){let t=new Int16Array(this.samplesPerChunk);for(let e=0;e<this.samplesPerChunk;e++)t[e]=Math.max(-32768,Math.min(32767,Math.round(this.buffer[e]*32768)));e=t.buffer}else e=this.buffer.buffer,this.buffer=new Float32Array(this.samplesPerChunk);this.port.postMessage(e,[e]),this.bufferIndex=0}};registerProcessor(`decibri-processor`,e);";

module.exports = { WORKLET_SOURCE };
