"""Type stubs for the decibri exception hierarchy."""


class DecibriError(Exception): ...


class SampleRateOutOfRange(DecibriError): ...
class ChannelsOutOfRange(DecibriError): ...
class MultichannelNotSupported(DecibriError): ...
class FramesPerBufferOutOfRange(DecibriError): ...
class AgcTargetOutOfRange(DecibriError): ...
class LimiterCeilingOutOfRange(DecibriError): ...
class InvalidFormat(DecibriError): ...


class DeviceError(DecibriError): ...


class MicrophoneNotFound(DeviceError): ...
class SpeakerNotFound(DeviceError): ...
class MultipleDevicesMatch(DeviceError): ...
class DeviceIndexOutOfRange(DeviceError): ...
class NoMicrophoneFound(DeviceError): ...
class NoSpeakerFound(DeviceError): ...
class NotAnInputDevice(DeviceError): ...
class DeviceEnumerationFailed(DeviceError): ...
class AlreadyRunning(DecibriError): ...
class StreamOpenFailed(DecibriError): ...
class StreamStartFailed(DecibriError): ...
class PermissionDenied(DecibriError): ...
class MicrophoneStreamClosed(DecibriError): ...
class SpeakerStreamClosed(DecibriError): ...
class DeviceFailed(DecibriError): ...
class VadSampleRateUnsupported(DecibriError): ...
class VadThresholdOutOfRange(DecibriError): ...
class FileReadFailed(DecibriError): ...
class WavInvalid(DecibriError): ...
class VadNotConfigured(DecibriError): ...
class FileConsumed(DecibriError): ...


class OrtError(DecibriError): ...


class OrtInitFailed(OrtError): ...
class OrtSessionBuildFailed(OrtError): ...
class OrtThreadsConfigFailed(OrtError): ...
class VadModelLoadFailed(OrtError):
    path: str
class ModelLoadFailed(OrtError):
    path: str
class OrtInferenceFailed(OrtError): ...
class OrtTensorCreateFailed(OrtError): ...
class OrtTensorExtractFailed(OrtError): ...


class OrtPathError(OrtError): ...


class OrtLoadFailed(OrtPathError):
    path: str


class OrtPathInvalid(OrtPathError):
    path: str
    reason: str


class ForkAfterOrtInit(DecibriError): ...
class OnnxBackendFailed(DecibriError): ...
