"""Type stubs for the decibri exception hierarchy (Phase 2)."""


class DecibriError(Exception): ...


class SampleRateOutOfRange(DecibriError): ...
class ChannelsOutOfRange(DecibriError): ...
class FramesPerBufferOutOfRange(DecibriError): ...
class InvalidFormat(DecibriError): ...


class DeviceError(DecibriError): ...


class DeviceNotFound(DeviceError): ...
class OutputDeviceNotFound(DeviceError): ...
class MultipleDevicesMatch(DeviceError): ...
class DeviceIndexOutOfRange(DeviceError): ...
class NoMicrophoneFound(DeviceError): ...
class NoOutputDeviceFound(DeviceError): ...
class NotAnInputDevice(DeviceError): ...
class DeviceEnumerationFailed(DeviceError): ...
class AlreadyRunning(DecibriError): ...
class StreamOpenFailed(DecibriError): ...
class StreamStartFailed(DecibriError): ...
class PermissionDenied(DecibriError): ...
class CaptureStreamClosed(DecibriError): ...
class OutputStreamClosed(DecibriError): ...
class VadSampleRateUnsupported(DecibriError): ...
class VadThresholdOutOfRange(DecibriError): ...


class OrtError(DecibriError): ...


class OrtInitFailed(OrtError): ...
class OrtSessionBuildFailed(OrtError): ...
class OrtThreadsConfigFailed(OrtError): ...
class VadModelLoadFailed(OrtError):
    path: str
class OrtInferenceFailed(OrtError): ...
class OrtTensorCreateFailed(OrtError): ...
class OrtTensorExtractFailed(OrtError): ...


class OrtPathError(OrtError): ...


class OrtLoadFailed(OrtPathError):
    path: str


class OrtPathInvalid(OrtPathError):
    path: str
    reason: str


class ForkAfterOrtInit(DecibriError): ...
