"""Type stubs for the decibri exception hierarchy (Phase 2)."""


class DecibriError(Exception): ...


class SampleRateOutOfRange(DecibriError): ...
class ChannelsOutOfRange(DecibriError): ...
class FramesPerBufferOutOfRange(DecibriError): ...
class InvalidFormat(DecibriError): ...
class DeviceNotFound(DecibriError): ...
class OutputDeviceNotFound(DecibriError): ...
class MultipleDevicesMatch(DecibriError): ...
class DeviceIndexOutOfRange(DecibriError): ...
class NoMicrophoneFound(DecibriError): ...
class NoOutputDeviceFound(DecibriError): ...
class NotAnInputDevice(DecibriError): ...
class DeviceEnumerationFailed(DecibriError): ...
class AlreadyRunning(DecibriError): ...
class StreamOpenFailed(DecibriError): ...
class StreamStartFailed(DecibriError): ...
class PermissionDenied(DecibriError): ...
class CaptureStreamClosed(DecibriError): ...
class OutputStreamClosed(DecibriError): ...
class VadSampleRateUnsupported(DecibriError): ...
class VadThresholdOutOfRange(DecibriError): ...


class OrtError(DecibriError): ...


class OrtInitFailed(OrtError): ...
class OrtSessionBuildFailed(OrtError): ...
class OrtThreadsConfigFailed(OrtError): ...
class VadModelLoadFailed(OrtError): ...
class OrtInferenceFailed(OrtError): ...
class OrtTensorCreateFailed(OrtError): ...
class OrtTensorExtractFailed(OrtError): ...


class OrtPathError(OrtError): ...


class OrtLoadFailed(OrtPathError):
    path: str


class OrtPathInvalid(OrtPathError):
    path: str
    reason: str
