/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Native bridge class exposed to Node.js via napi-rs. */
export declare class DecibriBridge {
  constructor(options?: DecibriOptions | undefined | null)
  /** Start capturing audio. The callback receives `(err, chunk)` for each buffer. */
  start(callback: (err: Error | null, chunk: Buffer) => void): void
  /** Stop capturing audio. */
  stop(): void
  /** Whether the microphone is currently capturing. */
  get isOpen(): boolean
  /** List all available audio input devices. */
  static devices(): Array<DeviceInfoJs>
  /** Version information. */
  static version(): VersionInfoJs
}

/** Options passed from JS constructor. */
export interface DecibriOptions {
  sampleRate?: number
  channels?: number
  framesPerBuffer?: number
  format?: string
  device?: any
}

/** Device info returned to JS. */
export interface DeviceInfoJs {
  index: number
  name: string
  maxInputChannels: number
  defaultSampleRate: number
  isDefault: boolean
}

/** Version info returned to JS. */
export interface VersionInfoJs {
  decibri: string
  portaudio: string
}
